# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: echoforge.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'echoforge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65\x63hoforge.proto\x12\x0fruvon.echoforge\"\xd1\x01\n\nMarketEcho\x12\x12\n\npattern_id\x18\x01 \x01(\t\x12\x1e\n\x16gross_delta_prediction\x18\x02 \x01(\x02\x12!\n\x19\x65stimated_frictional_drag\x18\x03 \x01(\x02\x12\x15\n\rnet_aliveness\x18\x04 \x01(\x02\x12\x17\n\x0f\x65xecution_count\x18\x05 \x01(\r\x12\x12\n\nregime_tag\x18\x06 \x01(\t\x12\x12\n\ndecay_rate\x18\x07 \x01(\x02\x12\x14\n\x0clast_updated\x18\x08 \x01(\x04\"\x83\x01\n\nSharedEcho\x12\x12\n\npattern_id\x18\x01 \x01(\t\x12\x15\n\rnet_aliveness\x18\x02 \x01(\x02\x12\x12\n\nregime_tag\x18\x03 \x01(\t\x12\x12\n\ndecay_rate\x18\x04 \x01(\x02\x12\x11\n\ttimestamp\x18\x05 \x01(\x04\x12\x0f\n\x07node_id\x18\x06 \x01(\t\"\xa6\x01\n\nMarketTick\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0b\n\x03\x62id\x18\x02 \x01(\x02\x12\x0b\n\x03\x61sk\x18\x03 \x01(\x02\x12\x12\n\nlast_price\x18\x04 \x01(\x02\x12\x12\n\nbuy_volume\x18\x05 \x01(\x02\x12\x13\n\x0bsell_volume\x18\x06 \x01(\x02\x12\x0c\n\x04side\x18\x07 \x01(\t\x12\x11\n\ttimestamp\x18\x08 \x01(\x04\x12\x10\n\x08\x65xchange\x18\t \x01(\t\",\n\tBookLevel\x12\r\n\x05price\x18\x01 \x01(\x02\x12\x10\n\x08quantity\x18\x02 \x01(\x02\"\x9c\x01\n\x11OrderBookSnapshot\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12(\n\x04\x62ids\x18\x02 \x03(\x0b\x32\x1a.ruvon.echoforge.BookLevel\x12(\n\x04\x61sks\x18\x03 \x03(\x0b\x32\x1a.ruvon.echoforge.BookLevel\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\x12\x10\n\x08\x65xchange\x18\x05 \x01(\t\"\xde\x01\n\x0bNodeMetrics\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x11\n\tuptime_ms\x18\x02 \x01(\x04\x12\x1b\n\x13tick_latency_p99_ms\x18\x03 \x01(\x02\x12\x18\n\x10\x61\x63tive_sentinels\x18\x04 \x01(\r\x12\x1a\n\x12\x65\x63ho_aliveness_avg\x18\x05 \x01(\x02\x12\x17\n\x0f\x63onsensus_state\x18\x06 \x01(\t\x12\x16\n\x0e\x63ompute_tflops\x18\x07 \x01(\x02\x12\x14\n\x0c\x61\x63tive_peers\x18\x08 \x01(\r\x12\x11\n\ttimestamp\x18\t \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echoforge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MARKETECHO']._serialized_start=37
  _globals['_MARKETECHO']._serialized_end=246
  _globals['_SHAREDECHO']._serialized_start=249
  _globals['_SHAREDECHO']._serialized_end=380
  _globals['_MARKETTICK']._serialized_start=383
  _globals['_MARKETTICK']._serialized_end=549
  _globals['_BOOKLEVEL']._serialized_start=551
  _globals['_BOOKLEVEL']._serialized_end=595
  _globals['_ORDERBOOKSNAPSHOT']._serialized_start=598
  _globals['_ORDERBOOKSNAPSHOT']._serialized_end=754
  _globals['_NODEMETRICS']._serialized_start=757
  _globals['_NODEMETRICS']._serialized_end=979
# @@protoc_insertion_point(module_scope)
